spring:
  application:
    name: hireup

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-request: true
      force-response: true

  data:
    redis:
      host: localhost  # Redis 서버 주소 (Docker 사용 시 컨테이너 이름)
      port: 6379       # Redis 기본 포트
      password:        # 비밀번호가 있다면 입력
      timeout: 6000ms  # 연결 타임아웃
    cache:
      type: redis      # 캐시 저장소를 Redis로 설정

  elasticsearch:
    uris: http://localhost:9200

  admin:
    token: ${ADMIN_TOKEN}

  base:
    url: ${BASE_URL}

  jwt:
    secret: ${JWT_SECRET}

  openweathermap:
    key: ${OPENWEATHERMAP_KEY}